# Generated by Django 3.0.5 on 2021-04-28 15:29

from django.db import migrations, models
import djongo.models.fields
import doctorRegistration.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('hospital_id', models.CharField(default=None, max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(default=None, max_length=50)),
                ('specilisation', models.CharField(max_length=100)),
                ('patients', djongo.models.fields.ArrayField(model_container=doctorRegistration.models.Patient)),
                ('registrationConfirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='doctorNotConfirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(max_length=15)),
                ('hashValue', models.CharField(max_length=200)),
            ],
        ),
    ]
