# Generated by Django 3.0.5 on 2021-05-08 19:45

from django.db import migrations
import djongo.models.fields
import doctorRegistration.models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorRegistration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='patients',
            field=djongo.models.fields.ArrayField(default=list, model_container=doctorRegistration.models.Patient),
        ),
    ]
