# Generated by Django 3.0.5 on 2021-05-19 11:39

import PatientRegistration.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(default='Null', max_length=2)),
                ('password', models.CharField(default='None', max_length=30)),
                ('email', models.EmailField(default='doctorgeek1947@gmail.com', max_length=254)),
                ('hospitalRegistered', models.CharField(default='None', max_length=15)),
                ('location', djongo.models.fields.EmbeddedField(model_container=PatientRegistration.models.location)),
                ('symptoms', djongo.models.fields.EmbeddedField(model_container=PatientRegistration.models.Symptoms)),
                ('symptoms_explanation', models.CharField(default='None', max_length=400)),
                ('doctorAllocatedID', models.CharField(default='None', max_length=20)),
                ('doctorAssigned', models.BooleanField(default=False)),
                ('disease_actual', models.CharField(default='No Prediction', max_length=100)),
                ('initiateTreatment', models.BooleanField(default=False)),
                ('complaint_notification', models.CharField(default='No Complaint Registered', max_length=100)),
                ('updates_from_doctors', djongo.models.fields.ArrayField(default=list, model_container=PatientRegistration.models.update)),
                ('regisitraionComplete', models.BooleanField(default=False)),
                ('medicine_list', djongo.models.fields.ArrayField(default=list, model_container=PatientRegistration.models.medicines)),
            ],
        ),
    ]
