# Generated by Django 3.0.5 on 2021-06-26 13:39

import HospitalDashboard.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('hid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(default='null', max_length=20)),
                ('hospital_name', models.CharField(max_length=40)),
                ('location', djongo.models.fields.EmbeddedField(model_container=HospitalDashboard.models.Location)),
                ('mailid', models.EmailField(default=None, max_length=254)),
                ('beds', djongo.models.fields.EmbeddedField(model_container=HospitalDashboard.models.Beds)),
                ('security', models.CharField(max_length=20)),
                ('notifications', djongo.models.fields.ArrayField(default=list, model_container=HospitalDashboard.models.Notification)),
                ('doctors', djongo.models.fields.ArrayField(default=list, model_container=HospitalDashboard.models.Doctors)),
                ('patient', djongo.models.fields.ArrayField(default=list, model_container=HospitalDashboard.models.Patient)),
                ('complaint_on_doctors', djongo.models.fields.ArrayField(default=list, model_container=HospitalDashboard.models.DoctorsComplaint)),
                ('protocol_breached', djongo.models.fields.ArrayField(default=list, model_container=HospitalDashboard.models.protocol)),
            ],
        ),
    ]
